INSERT INTO USUARIO VALUES(1,'francisco.j.leiva@hotmail.com','FJLN01',TO_DATE('15-03-2021 9:30:00',' DD-MM-YYYY HH:MI:SS'),TO_DATE('15-03-2021 9:30:00',' DD-MM-YYYY HH:MI:SS'),TO_DATE('15-03-2021 9:30:00',' DD-MM-YYYY HH:MI:SS'));

INSERT INTO CONTENIDO VALUES(1,'Semana 1','Presentación Estructuración del módulo, Información Importante, Ambientes y herramientas, Prueba de diagnóstico /Prueba de diagnostico y retroalimentación, Resultada de dinamica clase anterior, Actividades',TO_DATE('24-03-2021 9:30:00','DD-MM-YYYY HH:MI:SS'),TO_DATE('25-03-2021 11:00:00','DD-MM-YYYY HH:MI:SS'));
INSERT INTO APUNTE VALUES(1,1,'Apuntes Semana 1','ninguno',TO_DATE('24-03-2021 9:30:00','DD-MM-YYYY HH:MI:SS'),TO_DATE('25-03-2021 11:00:00','DD-MM-YYYY HH:MI:SS'));
INSERT INTO APUNTE_TIPO VALUES(1,'ninguno',TO_DATE('24-03-2021 9:30:00','DD-MM-YYYY HH:MI:SS'),TO_DATE('25-03-2021 11:00:00','DD-MM-YYYY HH:MI:SS'),1);

INSERT INTO CONTENIDO VALUES(2,'Semana 2','Contexto de Sistemas de hipertextos,Modelo y Arquitectura de Sistemas Hypertext y Dinámica practica ',TO_DATE('31-03-2021 9:30:00','DD-MM-YYYY HH:MI:SS',TO_DATE('01-04-2021 11:00:00','DD-MM-YYYY HH:MI:SS'));
INSERT INTO APUNTE VALUES(2,2,'Apuntes Semana 2','https://www.youtube.com/watch?v=APBWeiNmkco',TO_DATE('31-03-2021 9:30:00','DD-MM-YYYY HH:MI:SS',TO_DATE('01-04-2021 11:00:00','DD-MM-YYYY HH:MI:SS'));
INSERT INTO APUNTE_TIPO VALUES(2,'video',TO_DATE('31-03-2021 9:30:00','DD-MM-YYYY HH:MI:SS',TO_DATE('01-04-2021 11:00:00','DD-MM-YYYY HH:MI:SS'));

INSERT INTO CONTENIDO VALUES(3,'Semana 3','Medios, Tecnología y Desarrollo Web.Dinámica practica.Audio, Video, Imagen.Dinámica practica.',TO_DATE('7-04-2021 9:30:00','DD-MM-YYYY HH:MI:SS',TO_DATE('8-04-2021 11:00:00','DD-MM-YYYY HH:MI:SS'));
INSERT INTO APUNTE VALUES(3,3,'Curso HTML','https://www.youtube.com/watch?v=rbuYtrNUxg4&t=382s',TO_DATE('7-04-2021 9:30:00','DD-MM-YYYY HH:MI:SS',TO_DATE('8-04-2021 11:00:00','DD-MM-YYYY HH:MI:SS'));
INSERT INTO APUNTE_TIPO VALUES(3,'video',TO_DATE('7-04-2021 9:30:00','DD-MM-YYYY HH:MI:SS',TO_DATE('8-04-2021 11:00:00','DD-MM-YYYY HH:MI:SS'));

INSERT INTO CONTENIDO VALUES(4,'Semana 4','Presentación de evaluación, Dinámica practica.Fundamentos de HTML, Edición de Video con OpenShot, Dudas respecto a dinamica y Evaluación.',TO_DATE('14-04-2021 9:30:00','DD-MM-YYYY HH:MI:SS',TO_DATE('15-04-2021 11:00:00','DD-MM-YYYY HH:MI:SS'));
INSERT INTO APUNTE VALUES (4,4,'Tutorial openshot','https://www.youtube.com/watch?v=YSuCG3X2ZgA',TO_DATE('14-04-2021 9:30:00','DD-MM-YYYY HH:MI:SS',TO_DATE('15-04-2021 11:00:00','DD-MM-YYYY HH:MI:SS'));
INSERT INTO APUNTE_TIPO VALUES(4,'video',TO_DATE('14-04-2021 9:30:00','DD-MM-YYYY HH:MI:SS',TO_DATE('15-04-2021 11:00:00','DD-MM-YYYY HH:MI:SS'));

INSERT INTO CONTENIDO VALUES(5,'Semana 5','Presentacion evaluacion',TO_DATE('21-04-2021 9:30:00','DD-MM-YYYY HH:MI:SS',TO_DATE('22-04-2021 11:00:00','DD-MM-YYYY HH:MI:SS'));
INSERT INTO APUNTE VALUES(5,5,'ninguna','ninguno',TO_DATE('21-04-2021 9:30:00','DD-MM-YYYY HH:MI:SS',TO_DATE('22-04-2021 11:00:00','DD-MM-YYYY HH:MI:SS'));
INSERT INTO APUNTE_TIPO VALUES (5,'ninguno',TO_DATE('21-04-2021 9:30:00','DD-MM-YYYY HH:MI:SS',TO_DATE('22-04-2021 11:00:00','DD-MM-YYYY HH:MI:SS'));

INSERT INTO CONTENIDO VALUES (6,'Semana 6','Desarrollo /Metodologías/ proyecto o producto de Software, Desarrollo de proyectos/software Multimedia, Retroalimentación general de evaluación 1, *Aplicaciones, Evaluación Acumulativa',TO_DATE('28-04-2021 9:30:00','DD-MM-YYYY HH:MI:SS',TO_DATE('29-04-2021 11:00:00','DD-MM-YYYY HH:MI:SS'));
INSERT INTO APUNTE VALUES (6,6,'Revision de actividades practicas','ninguno',TO_DATE('28-04-2021 9:30:00','DD-MM-YYYY HH:MI:SS',TO_DATE('29-04-2021 11:00:00','DD-MM-YYYY HH:MI:SS'));
INSERT INTO APUNTE_TIPO VALUES (6,'ninguno',TO_DATE('28-04-2021 9:30:00','DD-MM-YYYY HH:MI:SS',TO_DATE('29-04-2021 11:00:00','DD-MM-YYYY HH:MI:SS'));